version: '3.9'
services:
  web:
    restart: on-failure
    build:
      context: services/web/
      dockerfile: Dockerfile
    container_name: "web"
    ports:
      - "8000:8000" # проблемы с портом
    environment:
      KAFKA_BOOTSTRAP_SERVERS: $KAFKA_BOOTSTRAP_SERVERS
      TEXT_TOPIC: $TEXT_TOPIC
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  zookeeper:
    image: 'bitnami/zookeeper:3.7.0'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=$ALLOW_ANONYMOUS_LOGIN

  kafka:
    image: 'bitnami/kafka:2.8.0'
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=$KAFKA_ZOOKEEPER_CONNECT
      - ALLOW_PLAINTEXT_LISTENER=$ALLOW_PLAINTEXT_LISTENER
    depends_on:
      - zookeeper

#  moderator:
#    restart: on-failure
#    build:
#      context: services/moderator/
#      dockerfile: Dockerfile
#    container_name: "moderator"
#    ports:
#      - "9000:9000"
#    environment:
#      KAFKA_BOOTSTRAP_SERVERS: $KAFKA_BOOTSTRAP_SERVERS
#      TEXT_TOPIC: $TEXT_TOPIC
#      PREDICTION_TOPIC: $PREDICTION_TOPIC
#    command: uvicorn main:app --reload --host 0.0.0.0 --port 9000
